#  Copyright 2025 Google Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
#  NOTE: This is not an officially supported Google product

steps:
  # ---- Step 1: Build all three container images directly ----
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build RP Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fedcm-demo-rp${_ENV_SUFFIX}:$SHORT_SHA', './fedcm/fedcm-rp-demo']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build IdP Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fedcm-demo-idp${_ENV_SUFFIX}:$SHORT_SHA', './fedcm/fedcm-idp-demo']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build IdP-2 Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fedcm-demo-idp-2${_ENV_SUFFIX}:$SHORT_SHA', './fedcm/fedcm-another-idp-demo']

  # ---- Step 2: Push all three container images ----
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push RP Image'
    waitFor: ['Build RP Image']
    args: ['push', 'gcr.io/$PROJECT_ID/fedcm-demo-rp${_ENV_SUFFIX}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push IdP Image'
    waitFor: ['Build IdP Image']
    args: ['push', 'gcr.io/$PROJECT_ID/fedcm-demo-idp${_ENV_SUFFIX}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push IdP-2 Image'
    waitFor: ['Build IdP-2 Image']
    args: ['push', 'gcr.io/$PROJECT_ID/fedcm-demo-idp-2${_ENV_SUFFIX}:$SHORT_SHA']

  # ---- Step 3: Deploy all three services ----
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy RP Service'
    entrypoint: gcloud
    waitFor: ['Push RP Image']
    args:
      - 'run'
      - 'deploy'
      - 'fedcm-demo-rp${_ENV_SUFFIX}'
      - '--image=gcr.io/$PROJECT_ID/fedcm-demo-rp${_ENV_SUFFIX}:$SHORT_SHA'
      - '--region=us-central1'
      - '--env-vars-file=./fedcm/${_ENV_FILE_NAME}'
      - '--quiet'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy IdP Service'
    entrypoint: gcloud
    waitFor: ['Push IdP Image']
    args:
      - 'run'
      - 'deploy'
      - 'fedcm-demo-idp${_ENV_SUFFIX}'
      - '--image=gcr.io/$PROJECT_ID/fedcm-demo-idp${_ENV_SUFFIX}:$SHORT_SHA'
      - '--region=us-central1'
      - '--env-vars-file=./fedcm/${_ENV_FILE_NAME}'
      - '--quiet'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy IdP-2 Service'
    entrypoint: gcloud
    waitFor: ['Push IdP-2 Image']
    args:
      - 'run'
      - 'deploy'
      - 'fedcm-demo-idp-2${_ENV_SUFFIX}'
      - '--image=gcr.io/$PROJECT_ID/fedcm-demo-idp-2${_ENV_SUFFIX}:$SHORT_SHA'
      - '--region=us-central1'
      - '--env-vars-file=./fedcm/${_ENV_FILE_NAME}'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/fedcm-demo-rp${_ENV_SUFFIX}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fedcm-demo-idp${_ENV_SUFFIX}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fedcm-demo-idp-2${_ENV_SUFFIX}:$SHORT_SHA'